version: "3.10"

services:
  app:
    build: .
    volumes:
      - .:/core
      - ./static:/app/static
      - ./media:/app/media
    ports:
    - "8066:8066"
    command: bash -c "python manage.py migrate && gunicorn job.wsgi:application -w 4 -b 0.0.0.0:8066"